export const ADD_ROUTE ='/add'
export const DELETE_ROUTE ='/delete'
export const STORE_ROUTE ='/store'
export const AUTHREG_ROUTE ='/auth_reg'
export const ADD_CATEGORY_ROUTE = '/new_category'
export const ADD_MODEL_ROUTE = '/new_model'